### ISSUE TITLE
Failing test: 3.0.14

### ISSUE THREAD

**Issue by sanjayankur31** [jonathf/chaospy#183] opened 2019-10-27 19:43 UTC
While building the new version, 3.0.14, a test seems to fail:

```
+ pytest-3.8 tests
============================= test session starts ==============================
platform linux -- Python 3.8.0, pytest-4.6.6, py-1.8.0, pluggy-0.12.0
rootdir: /builddir/build/BUILD/chaospy-3.0.14
plugins: cov-2.8.1
collected 194 items
tests/test_dist.py ..................................................... [ 27%]
........................................................................ [ 64%]
..................................                                       [ 81%]
tests/test_orth.py .....                                                 [ 84%]
tests/test_poly.py ..............                                        [ 91%]
tests/test_stress.py ........                                            [ 95%]
tests/quad/test_interface.py .F......                                    [100%]
=================================== FAILURES ===================================
_________________ test_1d_gauss_hermite_quadrature[chebyshev] __________________
recurrence_algorithm = 'chebyshev'
    def test_1d_gauss_hermite_quadrature(recurrence_algorithm):
        distribution = Normal(3, 4)
>       abscissas, weights = quad_gaussian(
            10, distribution, recurrence_algorithm=recurrence_algorithm)
/builddir/build/BUILD/chaospy-3.0.14/tests/quad/test_interface.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/builddir/build/BUILD/chaospy-3.0.14/chaospy/quadrature/gaussian.py:184: in quad_gaussian
    abscissas, weights = coefficients_to_quadrature(coefficients)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
coeffs = array([[[ 3.00000000e+00,  3.00000000e+00,  3.00000000e+00,
          3.00000000e+00,  3.00000000e+00,  3.00000000e+00...00000000e+01,
          9.60000000e+01,  1.12000000e+02, -6.30700000e+03,
          5.66481576e+03,  7.80097342e+01]]])
    def coefficients_to_quadrature(coeffs):
        """
        Construct Gaussian quadrature abscissas and weights from three terms
        recurrence coefficients.
    
        Examples:
            >>> distribution = chaospy.Normal(0, 1)
            >>> coeffs = chaospy.construct_recurrence_coefficients(4, distribution)
            >>> print(numpy.around(coeffs, 4))
            [[[0. 0. 0. 0. 0.]
              [0. 1. 2. 3. 4.]]]
            >>> abscissas, weights = chaospy.coefficients_to_quadrature(coeffs)
            >>> print(numpy.around(abscissas, 4))
            [[-2.857  -1.3556 -0.      1.3556  2.857 ]]
            >>> print(numpy.around(weights, 4))
            [[0.0113 0.2221 0.5333 0.2221 0.0113]]
        """
        coeffs = numpy.asfarray(coeffs)
        if len(coeffs.shape) == 2:
            coeffs = coeffs.reshape(1, 2, -1)
        assert len(coeffs.shape) == 3, "shape %s not allowed" % coeffs.shape
        assert coeffs.shape[-1] >= 1
        abscissas = []
        weights = []
        for coeff in coeffs:
    
            if numpy.any(coeff[1] < 0) or numpy.any(numpy.isnan(coeff)):
>               raise numpy.linalg.LinAlgError(
                    "Invalid recurrence coefficients can not be used for "
                    "constructing Gaussian quadrature rule")
E               numpy.linalg.LinAlgError: Invalid recurrence coefficients can not be used for constructing Gaussian quadrature rule
/builddir/build/BUILD/chaospy-3.0.14/chaospy/quadrature/recurrence/jacobi.py:33: LinAlgError
=============================== warnings summary ===============================
tests/test_dist.py::test_dist_add[ChiSquared]
tests/test_dist.py::test_dist_sub[ChiSquared]
tests/test_dist.py::test_dist_mul[ChiSquared]
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/distributions/collection/chi_squared.py:18: RuntimeWarning: divide by zero encountered in true_divide
    output *= (x/nc)**(0.25*df-0.5)
tests/test_dist.py::test_dist_add[ChiSquared]
tests/test_dist.py::test_dist_sub[ChiSquared]
tests/test_dist.py::test_dist_mul[ChiSquared]
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/distributions/collection/chi_squared.py:19: RuntimeWarning: invalid value encountered in multiply
    output *= special.iv(0.5*df-1, (nc*x)**0.5)
tests/test_dist.py::test_dist_add[GeneralizedExponential]
tests/test_dist.py::test_dist_add[Wald]
tests/test_dist.py::test_dist_sub[GeneralizedExponential]
tests/test_dist.py::test_dist_sub[Wald]
tests/test_dist.py::test_dist_mul[GeneralizedExponential]
tests/test_dist.py::test_dist_mul[Wald]
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/quadrature/fejer.py:90: RuntimeWarning: invalid value encountered in true_divide
    weights /= numpy.sum(weights)
tests/test_dist.py::test_dist_add[GeneralizedExtreme]
tests/test_dist.py::test_dist_sub[GeneralizedExtreme]
tests/test_dist.py::test_dist_mul[GeneralizedExtreme]
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/distributions/collection/generalized_extreme.py:31: RuntimeWarning: invalid value encountered in true_divide
    return numpy.where(c == 0, x, -numpy.expm1(-c*x)/c)
tests/test_dist.py::test_dist_add[GeneralizedExtreme]
tests/test_dist.py::test_dist_sub[GeneralizedExtreme]
tests/test_dist.py::test_dist_mul[GeneralizedExtreme]
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/distributions/collection/generalized_extreme.py:31: RuntimeWarning: invalid value encountered in double_scalars
    return numpy.where(c == 0, x, -numpy.expm1(-c*x)/c)
tests/test_dist.py::test_dist_add[GeneralizedExtreme]
tests/test_dist.py::test_dist_sub[GeneralizedExtreme]
tests/test_dist.py::test_dist_mul[GeneralizedExtreme]
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/distributions/collection/generalized_extreme.py:19: RuntimeWarning: invalid value encountered in true_divide
    logpex2 = numpy.where(c == 0, -x, logex2/c)
tests/test_dist.py::test_dist_add[Wald]
tests/test_dist.py::test_dist_sub[Wald]
tests/test_dist.py::test_dist_mul[Wald]
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/distributions/collection/wald.py:29: RuntimeWarning: invalid value encountered in multiply
    out -= numpy.exp(2.0/mu)*special.ndtr(-isqx*trm2)
tests/test_dist.py::test_dist_add[Wald]
tests/test_dist.py::test_dist_sub[Wald]
tests/test_dist.py::test_dist_mul[Wald]
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/distributions/approximation.py:75: RuntimeWarning: invalid value encountered in greater
    indices = forward(x_data=lower) > 0
tests/test_stress.py::test_approx_quadrature
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/distributions/approximation.py:362: RuntimeWarning: invalid value encountered in true_divide
    floc = numpy.abs(floc / eps)
tests/test_stress.py::test_approx_quadrature
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/distributions/approximation.py:217: RuntimeWarning: invalid value encountered in less
    (xloc_ < xupper[:, indices]) & (xloc_ > xlower[:, indices]),
tests/test_stress.py::test_approx_quadrature
  /builddir/build/BUILD/chaospy-3.0.14/chaospy/distributions/approximation.py:217: RuntimeWarning: invalid value encountered in greater
    (xloc_ < xupper[:, indices]) & (xloc_ > xlower[:, indices]),
-- Docs: https://docs.pytest.org/en/latest/warnings.html
============== 1 failed, 193 passed, 30 warnings in 72.32 seconds ==============
```

This is using python3.8, numpy 1.17, scipy 1.2.1

It only seems to fails on arm7hl though: https://koji.fedoraproject.org/koji/taskinfo?taskID=38594760
It builds fine on x86_64: https://koji.fedoraproject.org/koji/taskinfo?taskID=38594895

I don't know if this is a coincidence.

**Comment by jonathf** [comment] 2019-10-28 14:35
I have little access to the arm7hl architecture, so I need your help.

Likely the problem is the parameter combination is numerically close illegal values which only get triggered on the arm platform.

In the failing test, can you try out other parameters for the Normal distribution than `(3,4)`? Like what happens with `(2,3) (3,2) (2,2)` etc. Let me know if any of the combinations work on ARM. If so, I'll issue a patch.

**Comment by sanjayankur31** [comment] 2019-10-28 17:02
I'll try them out and report back--hopefully before the end of the week :)

**Comment by alcir** [comment] 2019-10-29 09:34
Hello.
Testing on a RPi3 armv7hl architecture. However I'm using Python 3.7.4

```distribution = Normal(3, 4)``` test doesn't pass
```distribution = Normal(2, 3)``` test doesn't pass
```distribution = Normal(3, 2)``` test passed
```distribution = Normal(3, 2)``` test passed

In any case there are the warnings reported in the first post.

**Comment by jonathf** [comment] 2019-11-04 14:54
Okay. I've updated the distribution to `Normal(2, 2)` and made a v2.0.15 release.

I'm closing. Reopen if the tests still don't pass.

**Closed by jonathf** 2019-11-04 14:54 UTC
